### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by izhengfan** [izhengfan/vimrc#2]
- [x] check lsp and cquery (turns out ccls is better)
- [x] check coc.nvim (together with ccls, better then ycm )
- [ ] check ncm2-pyclang 
- [ ] use vimtex to replace latex-suite
